
export const colors = [
    {
        color:"black",
        colorCode:"#000000",
        image:null
    },
    {
        color:"silver",
        colorCode:"#c0c0c0",
        image:null
    },
    {
        color:"gray",
        colorCode:"#808080",
        image:null
    },
    {
        color:"red",
        colorCode:"ff0000",
        image:null
    },
    {
        color:"Gold",
        colorCode:"#ffd700",
        image:null
    },
    {
        color:"Blue",
        colorCode:"#0000ff",
        image:null
    },
    {
        color:"Graphite",
        colorCode:"#383838",
        image:null
    },
    {
        color:"white",
        colorCode:"#ffffff",
        image:null
    },
   
]